services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: technodwarf-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
    user: www-data

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx
    container_name: technodwarf-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: postgres:12.20-alpine
    container_name: technodwarf-postgres
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"